### ISSUE TITLE
Port over RFC samples from IETF and competitive solutions (MMark, Kramdown)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#38] opened 2017-10-06 16:12 UTC
There is plenty of value in porting the number of RFC samples from other example repositories:
* https://tools.ietf.org/tools/templates/ (the "authoritative" repo)
* https://github.com/miekg/mmark/tree/master/rfc
* https://github.com/cabo/kramdown-rfc2629/tree/master/examples

The porting should also include:
* implement a check against default XML / MMark / Kramdown for each document so that our output is directly comparable (and hopefully close to identical) for the corresponding RFC text source (.adoc vs .mkd)

With this we can compare and iteratively streamline our syntax to make it better than what MMark/Krandown does.

**Comment by opoudjis** [comment] 2017-10-22 12:28
> implement a check against default XML / MMark / Kramdown for each document so that our output is directly comparable (and hopefully close to identical) for the corresponding RFC text source (.adoc vs .mkd)

What do you mean by this, @ronaldtse ? Roundtripping, or eyeballing, or something else? Am I comparing the RFC XML output for the adoc and the mmark, for example?

**Comment by opoudjis** [comment] 2017-10-22 12:29
https://tools.ietf.org/tools/templates/ 

Not updated since 2015, I see, which means all its RFC XML is v1, which we haven't even implemented. I will do the most recent Davies and Mib documents, in any case.

**Comment by ronaldtse** [comment] 2017-10-22 12:43
We do not need support for V1, of course :-)

The intention is to compare our XML output against Kramdown/ MMark etc ‘s XML so we ensure that we can generate the same text. If there are any differences we should document and make sure that we’re not on the wrong side of those differences.

**Comment by opoudjis** [comment] 2017-10-22 13:31
Ported the two RFC XML v1 examples from https://tools.ietf.org/tools/templates/  anyway. Their Asciidoc roundtrip should prove illuminating; there may be a couple of fixes to the gem needed.

**Comment by opoudjis** [comment] 2017-10-24 12:16
Finished tuning converter based on the two RFC XML v1 examples. In the Davies file, major issue is that the block structure of Asciidoc and RFC XML are at odds: a paragraph cannot contain both text and a list in Asciidoc.

#56 remains open, and until resolved, the conversion mangles entities in the source file (as well as ampersands in the header.)

**Comment by ronaldtse** [comment] 2017-10-24 13:36
@opoudjis in AsciiDoc you could have a paragraph with a list and text using ["List Continuation"](http://asciidoctor.org/docs/user-manual/#list-continuation)?

**Comment by opoudjis** [comment] 2017-10-25 02:03
The issue is the other way around. A list continuation is inside the list. (I'm illustrating with v3, because v2's lists are disguisting):

```
* x
+
y
```
<t>
<ul>
<li><t>x</t>
<t>y</t>
</ul>
</t>
````

What RFC XML can also do is have text *outside* the list:

````
<t>
<ul>
<li><t>x</t>
</ul>y
</t>
```

There is simply no way of doing that in Asciidoc: it's not its document model. A list is a block, and once the list block ends, the parser moves on to a new paragraph.

I do not consider this a deal-breaker, just a "known issue".

**Comment by ronaldtse** [comment] 2017-10-25 03:23
Got it. I guess we don't need to generate 100% identical files to v1...

**Comment by opoudjis** [comment] 2017-10-25 04:08
To be clear: this is not a v1 vs v2 issue, it's a, RFC XML vs Asciidoc document model issue. Asciidoc just isn't as expressive in its document model as arbitrary XML. If that's a concern, we'll just say that the XML might need to be post-edited after generation.

**Comment by ronaldtse** [comment] 2017-10-25 04:59
@opoudjis what I meant is that the goal is to produce equally readable RFC in readable form (txt, pdf...) rather than have an RFC XML of an identical structure, so it's not necessary to make the XML identical.

**Comment by opoudjis** [comment] 2017-10-25 21:02
https://github.com/rfc-format 
https://www.ietf.org/archive/id/draft-hoffman-rfcexamples-04.txt 
https://www.rfc-editor.org/rse/format-faq/

**Comment by opoudjis** [comment] 2017-10-29 06:04
Ticket #66 addresses rspec comparison of xml2rfc output (as text) of these files with the XML generated from their source. This ticket is for the conversion of these files as examples.

**Comment by opoudjis** [comment] 2017-11-04 06:42
Kramdown done

**Comment by opoudjis** [comment] 2017-11-13 10:39
Hoffman v2 example done. The v3 example was in fact not wellformed XML (!) ; at any rate, we don't currently have a way of testing it.

There's a difference in spacing in my rendering of Hoffman that I can't track down.

**Comment by opoudjis** [comment] 2017-11-24 12:57
Have already done first two of nine https://github.com/rfc-format documents.

**Comment by opoudjis** [comment] 2017-12-03 20:46
The other rfc-format documents are more of the same, closing this.

**Closed by opoudjis** 2017-12-03 20:46 UTC
